# -*- coding: utf-8 -*-
"""retail_sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNFGmXCGiO7a42JRnyPne-zQM8h4lz2N

### **Project- Retail Sales Analysis**

## Section 1 — Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option('display.max_columns', None)

# Better numeric formatting
pd.options.display.float_format = '{:,.2f}'.format

"""# Section 2 — Load Datasets"""

from google.colab import files

uploaded = files.upload()

customers = pd.read_csv("customers.csv")
stores = pd.read_csv("stores.csv")
categories = pd.read_csv("categories.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
payments = pd.read_csv("payments.csv")
shipments = pd.read_csv("shipments.csv")

print(customers.shape)
print(stores.shape)
print(categories.shape)
print(products.shape)
print(orders.shape)
print(order_items.shape)
print(payments.shape)
print(shipments.shape)

"""## Section 3: Dataset Overview"""

datasets = {
    "Customers": customers,
    "Stores": stores,
    "Categories": categories,
    "Products": products,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Shipments": shipments
}

#Display the First 5 Rows
for name, df in datasets.items():
    print("=" * 80)
    print(f"{name.upper()} DATASET")
    print("=" * 80)
    display(df.head())

#Dataset Information
for name, df in datasets.items():
    print("=" * 80)
    print(f"{name.upper()} INFO")
    print("=" * 80)
    df.info()
    print("\n")

#Statistical Summary
for name, df in datasets.items():
    print("=" * 80)
    print(f"{name.upper()} SUMMARY")
    print("=" * 80)
    display(df.describe(include='all'))

#Check Data Types
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.dtypes.to_frame(name="Data Type"))

#Display Column Names
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.columns.tolist())

"""#Section 4: Data Quality Assessment"""

#Missing Values
missing_values = {}

for name, df in datasets.items():
    missing_values[name] = df.isnull().sum()

for name, missing in missing_values.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    print(missing)
    print()

#Duplicate Rows
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

#Dataset Memory Usage
for name, df in datasets.items():
    memory = df.memory_usage(deep=True).sum() / (1024 ** 2)
    print(f"{name}: {memory:.2f} MB")

"""##Section 5: Data Integration (Merge Datasets)


"""

# Merge Datasets
# Merge Orders with Customers
master_df = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

# Merge Stores
master_df = master_df.merge(
    stores,
    on="store_id",
    how="left",
    suffixes=("", "_store")
)

# Merge Payments
master_df = master_df.merge(
    payments,
    on="order_id",
    how="left"
)

# Merge Order Items
master_df = master_df.merge(
    order_items,
    on="order_id",
    how="left",
    suffixes=("", "_item")
)

# Merge Products
master_df = master_df.merge(
    products,
    on="product_id",
    how="left"
)

# Merge Categories
master_df = master_df.merge(
    categories,
    on="category_id",
    how="left"
)

# Merge Shipments
master_df = master_df.merge(
    shipments,
    on="order_id",
    how="left",
    suffixes=("", "_shipment")
)

master_df.isnull().sum().sort_values(ascending=False)

analysis_df = master_df.dropna(
    subset=["order_item_id"]
).copy()

analysis_df.shape

analysis_df.isnull().sum()

"""##Section 6: Exploratory Data Analysis (EDA)"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import os

# Create folder for saving charts
os.makedirs("EDA_Charts", exist_ok=True)

# Matplotlib Settings
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['figure.dpi'] = 150
plt.rcParams['axes.titlesize'] = 18
plt.rcParams['axes.labelsize'] = 13
plt.rcParams['xtick.labelsize'] = 11
plt.rcParams['ytick.labelsize'] = 11
plt.rcParams['legend.fontsize'] = 11

# Currency Formatter
currency = FuncFormatter(lambda x, pos: f'${x/1e6:.1f}M')

"""#create analysis dataframes"""

#order-level data
order_df = (
    orders
    .merge(payments, on='order_id')
    .merge(customers, on='customer_id')
    .merge(stores, on='store_id')
)

order_df.head()

order_df = order_df.rename(columns={
    'city_x': 'customer_city',
    'city_y': 'store_city'
})

#product-level data

product_df = (
    order_items
    .merge(
        products,
        on='product_id',
        how='left',
        suffixes=('_order', '_product')
    )
    .merge(
        categories,
        on='category_id',
        how='left'
    )
)

product_df['revenue'] = (
    product_df['qty'] *
    product_df['price_order']
)

product_df.head()

#shipment data
shipment_df = (
    shipments
    .merge(orders, on='order_id')
)

shipment_df.head()

# ==============================
# Key Performance Indicators
# ==============================
kpis = {

    "Total Revenue":
    order_df['amount'].sum(),

    "Total Orders":
    order_df['order_id'].nunique(),

    "Total Customers":
    customers['customer_id'].nunique(),

    "Total Products":
    products['product_id'].nunique(),

    "Total Stores":
    stores['store_id'].nunique(),

    "Total Categories":
    categories['category_id'].nunique(),

    "Average Order Value":
    order_df['amount'].mean()

}

kpi_df = pd.DataFrame(
    kpis.items(),
    columns=['Metric','Value']
)

kpi_df

analysis_df['order_date'] = pd.to_datetime(
    analysis_df['order_date']
)

# ==============================
# Monthly Revenue Trend
# ==============================

order_df['order_date'] = pd.to_datetime(order_df['order_date'])

monthly_revenue = (
    order_df
    .groupby(
        order_df['order_date'].dt.to_period('M')
    )['amount']
    .sum()
    .reset_index()
)

monthly_revenue['order_date'] = (
    monthly_revenue['order_date']
    .astype(str)
)

plt.figure(figsize=(13,6))

plt.plot(
    monthly_revenue['order_date'],
    monthly_revenue['amount'],
    linewidth=3,
    marker='o'
)

ax = plt.gca()
ax.yaxis.set_major_formatter(currency)

plt.title("Monthly Revenue Trend")

plt.xlabel("Month")

plt.ylabel("Revenue")

plt.xticks(rotation=45)

plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    "EDA_Charts/01_Monthly_Revenue.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

#revenue by product category
category_revenue = (
    product_df
    .groupby("category_name", as_index=False)["revenue"]
    .sum()
    .sort_values("revenue", ascending=False)
)

plt.figure(figsize=(20,6))

bars = plt.bar(
    category_revenue["category_name"],
    category_revenue["revenue"]
)

ax = plt.gca()
ax.yaxis.set_major_formatter(currency)

plt.title("Revenue by Product Category", fontsize=18)

plt.xlabel("Category")

plt.ylabel("Revenue")

plt.xticks(rotation=45)

plt.grid(axis="y", alpha=0.3)

# Value labels
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x()+bar.get_width()/2,
        height,
        f"${height/1e6:.1f}M",
        ha='center',
        va='bottom',
        fontsize=8
    )

plt.tight_layout()

plt.savefig(
    "EDA_Charts/02_Revenue_by_Category.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#top 10 products by revenue
top_products = (
    product_df
    .groupby("product_id", as_index=False)["revenue"]
    .sum()
    .sort_values("revenue", ascending=False)
    .head(10)
)

plt.figure(figsize=(12,6))

bars = plt.barh(
    top_products["product_id"].astype(str),
    top_products["revenue"]
)

ax = plt.gca()
ax.xaxis.set_major_formatter(currency)

plt.title("Top 10 Products by Revenue")

plt.xlabel("Revenue")

plt.ylabel("Product ID")

plt.gca().invert_yaxis()

plt.grid(axis="x", alpha=0.3)

# Value labels
for bar in bars:
    width = bar.get_width()
    plt.text(
        width,
        bar.get_y()+bar.get_height()/2,
        f"${width/1e6:.1f}M",
        va='center',
        fontsize=8
    )

plt.tight_layout()

plt.savefig(
    "EDA_Charts/03_Top_Products.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#top 10 customers by revenue
customer_revenue = (
    order_df
    .groupby('customer_id', as_index=False)['amount']
    .sum()
    .sort_values('amount', ascending=False)
    .head(10)
)

plt.figure(figsize=(12,6))

bars = plt.barh(
    customer_revenue['customer_id'].astype(str),
    customer_revenue['amount']
)

ax = plt.gca()
ax.xaxis.set_major_formatter(currency)

plt.title("Top 10 Customers by Revenue")

plt.xlabel("Revenue")

plt.ylabel("Customer ID")

plt.gca().invert_yaxis()

plt.grid(axis='x', alpha=0.3)

for bar in bars:
    width = bar.get_width()
    plt.text(
        width,
        bar.get_y()+bar.get_height()/2,
        f"${width/1e6:.2f}M",
        va='center',
        fontsize=8
    )

plt.tight_layout()

plt.savefig(
    "EDA_Charts/04_Top_Customers.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#revenue by store
store_revenue = (
    order_df
    .groupby('store_id', as_index=False)['amount']
    .sum()
    .sort_values('amount', ascending=False)
)

plt.figure(figsize=(20,6))

bars = plt.bar(
    store_revenue['store_id'].astype(str),
    store_revenue['amount']
)

ax = plt.gca()
ax.yaxis.set_major_formatter(currency)

plt.title("Revenue by Store")

plt.xlabel("Store ID")

plt.ylabel("Revenue")

plt.xticks(rotation=90)

plt.grid(axis='y', alpha=0.3)

plt.tight_layout()

plt.savefig(
    "EDA_Charts/05_Revenue_by_Store.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#revenue by customer city
city_revenue = (
    order_df
    .groupby('customer_city', as_index=False)['amount']
    .sum()
    .sort_values('amount', ascending=False)
    .head(15)
)

plt.figure(figsize=(12,6))

bars = plt.bar(
    city_revenue['customer_city'],
    city_revenue['amount']
)

ax = plt.gca()
ax.yaxis.set_major_formatter(currency)

plt.title("Top 15 Customer Cities by Revenue")

plt.xlabel("Customer City")
plt.ylabel("Revenue")

plt.xticks(rotation=45)

plt.grid(axis='y', alpha=0.3)

plt.tight_layout()

plt.savefig(
    "EDA_Charts/06_Revenue_by_Customer_City.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#shipment_status_distribution
shipment_status = (
    shipment_df['status']
    .value_counts()
)

plt.figure(figsize=(8,8))

plt.pie(
    shipment_status.values,
    labels=shipment_status.index,
    autopct='%1.1f%%',
    startangle=90
)

plt.title("Shipment Status Distribution")

plt.savefig(
    "EDA_Charts/07_Shipment_Status.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#average selling price by category
avg_price_category = (
    product_df
    .groupby('category_name', as_index=False)['price_order']
    .mean()
    .sort_values('price_order', ascending=False)
)

plt.figure(figsize=(15,6))

bars = plt.bar(
    avg_price_category['category_name'],
    avg_price_category['price_order']
)

plt.title("Average Selling Price by Category")

plt.xlabel("Category")

plt.ylabel("Average Price")

plt.xticks(rotation=45)

plt.grid(axis='y', alpha=0.3)

for bar in bars:
    plt.text(
        bar.get_x()+bar.get_width()/2,
        bar.get_height(),
        f"${bar.get_height():.0f}",
        ha='center',
        va='bottom',
        fontsize=8
    )

plt.tight_layout()

plt.savefig(
    "EDA_Charts/08_Average_Price_by_Category.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

# ==========================================
# Top 10 Suppliers by Revenue
# ==========================================

supplier_revenue = (
    product_df
    .groupby('supplier_id', as_index=False)['revenue']
    .sum()
    .sort_values('revenue', ascending=False)
    .head(10)
)

plt.figure(figsize=(12,6))

bars = plt.barh(
    supplier_revenue['supplier_id'].astype(str),
    supplier_revenue['revenue']
)

ax = plt.gca()
ax.xaxis.set_major_formatter(currency)

plt.title("Top 10 Suppliers by Revenue", fontsize=18)

plt.xlabel("Revenue")

plt.ylabel("Supplier ID")

plt.gca().invert_yaxis()

plt.grid(axis='x', alpha=0.3)

# Value Labels
for bar in bars:
    width = bar.get_width()
    plt.text(
        width,
        bar.get_y() + bar.get_height()/2,
        f"${width/1e6:.2f}M",
        va='center',
        fontsize=8
    )

plt.tight_layout()

plt.savefig(
    "EDA_Charts/09_Top_Suppliers_by_Revenue.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

#customer signup trend
order_df['signup_date'] = pd.to_datetime(order_df['signup_date'])

signup_trend = (
    order_df
    .drop_duplicates('customer_id')
    .groupby(
        order_df
        .drop_duplicates('customer_id')['signup_date']
        .dt.to_period('M')
    )
    .size()
    .reset_index(name='customers')
)

signup_trend['signup_date'] = signup_trend['signup_date'].astype(str)

plt.figure(figsize=(18,6))

plt.plot(
    signup_trend['signup_date'],
    signup_trend['customers'],
    marker='o',
    linewidth=2
)

plt.title("Customer Signup Trend")

plt.xlabel("Month")

plt.ylabel("New Customers")

plt.xticks(rotation=45)

plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    "EDA_Charts/10_Customer_Signups.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

!pip install pillow

from PIL import Image
import os

image_files = [
    "EDA_Charts/01_Monthly_Revenue.png",
    "EDA_Charts/02_Revenue_by_Category.png",
    "EDA_Charts/03_Top_Products.png",
    "EDA_Charts/04_Top_Customers.png",
    "EDA_Charts/05_Revenue_by_Store.png",
    "EDA_Charts/06_Revenue_by_Customer_City.png",
    "EDA_Charts/07_Shipment_Status.png",
    "EDA_Charts/08_Average_Price_by_Category.png",
    "EDA_Charts/09_Top_Suppliers_by_Revenue.png",
    "EDA_Charts/10_Customer_Signups.png"
]

images = []

for file in image_files:
    img = Image.open(file)

    if img.mode != "RGB":
        img = img.convert("RGB")

    images.append(img)

images[0].save(
    "Retail_Sales_EDA_Report.pdf",
    save_all=True,
    append_images=images[1:]
)

print("✅ PDF created successfully!")

from google.colab import files

files.download("Retail_Sales_EDA_Report.pdf")